puts('Hello')
puts("Hello")
puts("Hello 'world'")
puts('Hello "world"')
puts('//')
puts('Hello '+'world')
puts('Hello '*3)
puts('Hello'[0])
puts('Hello'[1])
puts('Hello'[2])
puts('//')
puts('hello world'.capitalize())
puts('hello world'.upcase())
puts('Hello world'.length())
puts('Hello world'.sub('world', 'programming'))